app:
  name: user-service
  log_level: debug

http:
  host: "0.0.0.0"
  port: 8080

grpc:
  host: "0.0.0.0"
  port: 9090

database:
  name: "users"
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  ssl_mode: "disable"

admin:
  email: "admin@example.com"
  password: "admin"
