apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth-service
spec:
  type: backend
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [user-grpc-api]
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: auth-api
spec:
  type: openapi
  lifecycle: experimental
  owner: guests
  system: examples
  definition: ./docs//swagger/swagger.json