services:
    mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - rbac_mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: indal
      MONGO_INITDB_ROOT_PASSWORD: indal