POST http://localhost:8081/v1/auth/login
Content-Type: application/json

{
  "email": "indal@gmail.com",
  "password": "Indal@123"
}

###
POST http://localhost:8081/v1/auth/register
Content-Type: application/json

{
  "email": "indal@gmail.com",
  "first_name": "Indal",
  "middle_name": "Kumar",
  "last_name": "Yadav",
  "password": "Indal@123",
  "role": "user"
}