services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-grpc
    ports:
      - "16686:16686" # Jaeger UI
      - "4318:4318" # OTLP HTTP ingest (v1/traces)
    environment:
      - LOG_LEVEL=debug

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  svc-b-grpc:
    build: ./svc-b
    container_name: svc-b-grpc
    environment:
      - OTEL_SERVICE_NAME=svc-b-grpc
    depends_on:
      - jaeger
    ports:
      - "9091:9091"

  svc-a-grpc:
    build: ./svc-a
    container_name: svc-a-grpc
    environment:
      - OTEL_SERVICE_NAME=svc-a-grpc
    depends_on:
      - jaeger
      - svc-b-grpc
    ports:
      - "9090:9090"

volumes:
  es_data:
